/**
 * SupplyGuard AI — Operator Dashboard Mock Data
 * Module A (Member 1 - Frontend)
 */

export const kpiMetricsData = [
  {
    id: 'kpi_shipments',
    title: 'Total Shipments',
    value: '48',
    trend: '↑ 12%',
    trendType: 'positive',
    comparison: 'vs. last 7 days',
    icon: 'Package',
    bgAccent: 'from-emerald-500/10 via-teal-500/5 to-transparent',
    borderAccent: 'border-emerald-500/20',
    iconBg: 'bg-emerald-500/20 text-emerald-600'
  },
  {
    id: 'kpi_disruptions',
    title: 'Active Disruptions',
    value: '3',
    trend: '↓ 40%',
    trendType: 'positive', // Fewer disruptions is positive!
    comparison: 'vs. last 7 days',
    icon: 'AlertTriangle',
    bgAccent: 'from-rose-500/10 via-pink-500/5 to-transparent',
    borderAccent: 'border-rose-500/20',
    iconBg: 'bg-rose-500/20 text-rose-600'
  },
  {
    id: 'kpi_delivery',
    title: 'On-Time Delivery',
    value: '92%',
    trend: '↑ 5%',
    trendType: 'positive',
    comparison: 'vs. last 7 days',
    icon: 'Route',
    bgAccent: 'from-sky-500/10 via-blue-500/5 to-transparent',
    borderAccent: 'border-sky-500/20',
    iconBg: 'bg-sky-500/20 text-sky-600'
  },
  {
    id: 'kpi_fleet',
    title: 'Fleet Utilization',
    value: '78%',
    trend: '↑ 8%',
    trendType: 'positive',
    comparison: 'vs. last 7 days',
    icon: 'Truck',
    bgAccent: 'from-indigo-500/10 via-purple-500/5 to-transparent',
    borderAccent: 'border-indigo-500/20',
    iconBg: 'bg-indigo-500/20 text-indigo-600'
  },
  {
    id: 'kpi_cold_chain',
    title: 'Cold Chain Health',
    value: '96%',
    trend: '↑ 3%',
    trendType: 'positive',
    comparison: 'vs. last 7 days',
    icon: 'Snowflake',
    bgAccent: 'from-teal-500/10 via-cyan-500/5 to-transparent',
    borderAccent: 'border-teal-500/20',
    iconBg: 'bg-teal-500/20 text-teal-600'
  }
];

export const recentDisruptionsData = [
  {
    id: 'dis_01',
    title: 'Port Congestion',
    location: 'Port of Singapore',
    severity: 'High',
    timeAgo: '2h ago',
    icon: 'Anchor',
    badgeClass: 'bg-rose-100 text-rose-700 border-rose-200'
  },
  {
    id: 'dis_02',
    title: 'Weather Alert',
    location: 'Rotterdam, Netherlands',
    severity: 'Medium',
    timeAgo: '5h ago',
    icon: 'Sun',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200'
  },
  {
    id: 'dis_03',
    title: 'Temperature Excursion',
    location: 'Container #SG12345',
    severity: 'Low',
    timeAgo: '8h ago',
    icon: 'Thermometer',
    badgeClass: 'bg-sky-100 text-sky-800 border-sky-200'
  }
];

export const shipmentOverviewData = [
  {
    id: 'SG-1001',
    route: 'Shanghai → Mumbai',
    status: 'On Track',
    statusBadge: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    eta: 'May 2, 2025',
    temp: '2°C'
  },
  {
    id: 'SG-1002',
    route: 'Dubai → Rotterdam',
    status: 'Delayed',
    statusBadge: 'bg-amber-100 text-amber-800 border-amber-200',
    eta: 'May 5, 2025',
    temp: '4°C'
  },
  {
    id: 'SG-1003',
    route: 'Los Angeles → Chicago',
    status: 'On Track',
    statusBadge: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    eta: 'Apr 30, 2025',
    temp: '-1°C'
  },
  {
    id: 'SG-1004',
    route: 'Singapore → Sydney',
    status: 'At Port',
    statusBadge: 'bg-sky-100 text-sky-800 border-sky-200',
    eta: 'May 3, 2025',
    temp: '3°C'
  }
];

export const notificationsMock = [
  {
    id: 'notif_1',
    title: 'Disruption Alert: Port of Singapore',
    detail: 'Rerouting recommendation generated by IBM Bob.',
    time: '10 mins ago',
    isUnread: true
  },
  {
    id: 'notif_2',
    title: 'Temperature Excursion Resolved',
    detail: 'Container #SG12345 cooling unit re-stabilized to 2.4°C.',
    time: '1 hour ago',
    isUnread: false
  }
];

export const quickActionsData = [
  { id: 'qa_track', label: 'Track Shipment', icon: 'Package', route: '/shipments', color: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
  { id: 'qa_disruptions', label: 'View Disruptions', icon: 'AlertTriangle', route: '/disruptions', color: 'text-rose-600 bg-rose-50 border-rose-200' },
  { id: 'qa_routes', label: 'Get Route Suggestion', icon: 'Route', route: '/routes', color: 'text-sky-600 bg-sky-50 border-sky-200' },
  { id: 'qa_fleet', label: 'Fleet Optimization', icon: 'Truck', route: '/fleet', color: 'text-indigo-600 bg-indigo-50 border-indigo-200' },
  { id: 'qa_cold_chain', label: 'Cold Chain Monitor', icon: 'Snowflake', route: '/cold-chain', color: 'text-teal-600 bg-teal-50 border-teal-200' },
  { id: 'qa_bob', label: 'Ask IBM Bob', icon: 'Brain', route: '/ai-assistant', color: 'text-sky-600 bg-sky-50 border-sky-200' }
];
